import '../constants/assets_constant.dart';

class ImageModel {
  String image;
  String category;

  ImageModel({
    required this.image,
    required this.category,
  });
}

List<ImageModel> imageList = [
  ImageModel(image: Assets.assetsImagesAnimalAnimal01, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal02, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal03, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal04, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal05, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal06, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal07, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal08, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal09, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal10, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal11, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal12, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal13, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal14, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal15, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal16, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal17, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal18, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal19, category: "Animal"),
  ImageModel(image: Assets.assetsImagesAnimalAnimal20, category: "Animal"),

  ImageModel(image: Assets.assetsImagesPanoramaPanorama01, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama02, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama03, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama04, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama05, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama06, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama07, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama08, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama09, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama10, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama11, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama12, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama13, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama14, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama15, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama16, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama17, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama18, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama19, category: "Panorama"),
  ImageModel(image: Assets.assetsImagesPanoramaPanorama20, category: "Panorama"),
  
  ImageModel(image: Assets.assetsImagesVehicleVehicle01, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle02, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle03, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle04, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle05, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle06, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle07, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle08, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle09, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle10, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle11, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle12, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle13, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle14, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle15, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle16, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle17, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle18, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle19, category: "Vehicle"),
  ImageModel(image: Assets.assetsImagesVehicleVehicle20, category: "Vehicle"),
];